name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: JohnnyMorganz/stylua-action@v4
        with:
          version: v2.1.0
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --check lua plugin tests
      - run: sudo apt-get update && sudo apt-get install --yes lua-check
      - run: luacheck lua plugin tests

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        neovim: [v0.11.3, stable]
    steps:
      - uses: actions/checkout@v5
      - uses: rhysd/action-setup-vim@v1
        with:
          version: ${{ matrix.neovim }}
          neovim: true
      - run: make deps
      - run: make test
